(function () {
  "use strict";
  const t=(es,en)=>({es,en});
  const copy={hub:t("Volver al Hub","Return to the Hub"),eyebrow:t("Curso de fundamentos · 190 min","Foundation course · 190 min"),title:t("Ecodiseño, Circularidad y Materiales Aeronáuticos","Eco-Design, Circularity & Aerospace Materials"),lead:t("Aprende a justificar decisiones de diseño y materiales considerando el sistema completo, los requisitos técnicos y la calidad de la evidencia.","Learn to justify design and material decisions by considering the whole system, technical requirements and evidence quality."),frame:t("Enmarcar","Frame"),compare:t("Comparar","Compare"),design:t("Diseñar","Design"),evidence:t("Evidenciar","Evidence"),review:t("Revisar","Review"),beforeStart:t("Antes de comenzar","Before you start"),objectivesTitle:t("Objetivos de aprendizaje","Learning objectives"),scopeNote:t("Este curso ofrece fundamentos educativos y práctica guiada. No acredita competencia de ingeniería ni sustituye requisitos de aeronavegabilidad, procesos aprobados o evaluación especializada.","This course provides educational foundations and guided practice. It does not certify engineering competence or replace airworthiness requirements, approved processes or specialist assessment."),progress:t("módulos visitados","modules visited"),previous:t("Anterior","Previous"),next:t("Siguiente módulo","Next module"),finish:t("Ir al ejercicio final","Go to final exercise"),module:t("Módulo","Module"),final:t("Ejercicio final","Final exercise"),concepts:t("Marco técnico","Technical framework"),miniCase:t("Mini-caso aplicado","Applied mini-case"),analysis:t("Análisis guiado","Guided analysis"),check:t("Comprobación breve","Short knowledge check"),checkAction:t("Comprobar respuestas","Check answers"),answerAll:t("Responde las dos preguntas para continuar.","Answer both questions to continue."),result:t(n=>`${n} de 2 respuestas correctas. Revisa el feedback: es práctica, no una calificación.`,n=>`${n} of 2 answers correct. Review the feedback: this is practice, not a grade.`),correct:t("Correcto. ","Correct. "),reviewAnswer:t("Revisar. ","Review. "),finalAction:t("Revisar el ejercicio integrado","Review the integrated exercise"),finalIncomplete:t("Responde todas las decisiones antes de revisar el ejercicio.","Answer every decision before reviewing the exercise."),completedTitle:t("Curso completado","Course completed"),completedBody:t("Has completado los seis módulos y revisado el ejercicio integrado. La finalización se guarda en este navegador; no es una calificación, certificación ni acreditación de competencia.","You have completed all six modules and reviewed the integrated exercise. Completion is stored in this browser; it is not a grade, certification or accreditation of competence."),revisit:t("Puedes volver a cualquier módulo para revisar conceptos y feedback.","You can return to any module to review concepts and feedback.")};
  const objectives=t(["Delimitar una comparación de ciclo de vida sin desplazar impactos.","Ordenar estrategias de circularidad por conservación de valor.","Convertir criterios ambientales y sociales en requisitos verificables junto con seguridad y aeronavegabilidad.","Comparar materiales aeronáuticos con sus límites de trazabilidad, durabilidad y recuperación.","Diseñar para mantenimiento, reparación, actualización y desmontaje.","Documentar decisiones proporcionales a la calidad de la evidencia."],["Frame a life-cycle comparison without shifting burdens.","Order circularity strategies by value retention.","Turn environmental and social criteria into verifiable requirements alongside safety and airworthiness.","Compare aerospace materials with their traceability, durability and recovery constraints.","Design for maintenance, repair, upgrade and disassembly.","Document decisions in proportion to evidence quality."]);
  const q=(question,esOptions,enOptions,correct,feedbackEs,feedbackEn)=>({q:t(question[0],question[1]),options:t(esOptions,enOptions),correct,feedback:t(feedbackEs,feedbackEn)});
  const modules=[
    {id:"life-cycle",title:t("Pensamiento de ciclo de vida en aeronáutica","Life-cycle thinking in aerospace"),intro:t("El ecodiseño empieza definiendo qué función se compara, durante cuánto tiempo y dentro de qué límites. Sin ese marco, una mejora local puede ocultar impactos en otra etapa.","Eco-design starts by defining the function being compared, for how long and within which boundaries. Without that frame, a local improvement can hide impacts elsewhere."),sections:t([
      ["Función y unidad de comparación","No compares solo kilogramos de material. Compara una función equivalente: por ejemplo, proteger un conducto durante un número definido de horas de vuelo, inspecciones y condiciones. La masa, la vida útil y el rendimiento cambian la cantidad necesaria para prestar esa función."],
      ["Límites del sistema","Incluye extracción y procesado, fabricación, integración, operación, mantenimiento y fin de vida cuando puedan cambiar la decisión. Declara exclusiones y sensibilidad: el transporte puede ser menor que la energía de uso en un caso y decisivo en otro."],
      ["Transferencia de cargas","Reducir masa puede disminuir combustible, pero requerir un material crítico, más energía de fabricación o una reparación imposible. Menor coste puede trasladar riesgo laboral o de suministro. Una mejora se acepta por el balance del sistema, no por una etiqueta aislada."],
      ["Incertidumbre aeronáutica","Vida de flota, perfil de misión, tasa de reparación y ruta de fin de vida rara vez son certezas. Usa escenarios y rangos, conserva las hipótesis y señala qué resultado cambia si una hipótesis falla."]
    ],[
      ["Function and comparison unit","Do not compare kilograms of material alone. Compare an equivalent function: for example, protecting a duct for a defined number of flight hours, inspections and conditions. Mass, lifetime and performance change how much is needed to deliver that function."],
      ["System boundaries","Include extraction and processing, manufacturing, integration, operation, maintenance and end of life when they can change the decision. State exclusions and sensitivity: transport may be minor beside use energy in one case and decisive in another."],
      ["Burden shifting","Lower mass may reduce fuel but require a critical material, more manufacturing energy or an unrepairable design. Lower cost may shift labour or supply risk. Accept an improvement through the system balance, not an isolated label."],
      ["Aerospace uncertainty","Fleet life, mission profile, repair rate and end-of-life route are rarely certain. Use scenarios and ranges, retain assumptions and identify which result changes if an assumption fails."]
    ]),flow:t([["Función","Servicio equivalente"],["Límites","Etapas incluidas"],["Escenarios","Uso y vida"],["Trade-offs","Impactos desplazados"]],[["Function","Equivalent service"],["Boundaries","Included stages"],["Scenarios","Use and life"],["Trade-offs","Shifted impacts"]]),caseTitle:t("Soporte aligerado","Lightweighted bracket"),case:t("Un soporte de composite reduce 1,8 kg frente al aluminio, pero necesita curado intensivo, inspección especializada y se sustituye completo tras daño. La flota vuela pocas horas al año.","A composite bracket saves 1.8 kg over aluminium but needs energy-intensive curing, specialist inspection and full replacement after damage. The fleet flies few hours per year."),analysis:t("Define primero función, vida y perfil de uso. Calcula si el beneficio operacional compensa fabricación y reemplazos; compara también reparación, residuos y suministro. No concluyas que aligerar es automáticamente mejor.","Define function, life and use profile first. Test whether operational benefit offsets manufacture and replacements; also compare repair, waste and supply. Do not conclude that lightweighting is automatically better."),questions:[q(["¿Qué comparación es más defendible?","Which comparison is more defensible?"],["1 kg de cada material","La misma función durante una vida y perfil definidos","Solo el precio de compra"],["1 kg of each material","The same function over a defined life and profile","Purchase price only"],1,"La perspectiva funcional evita comparar soluciones que prestan servicios distintos.","A functional perspective avoids comparing solutions that deliver different services."),q(["¿Qué revela transferencia de cargas?","What reveals burden shifting?"],["Una mejora de uso que aumenta impactos relevantes en fabricación o fin de vida","Cualquier reducción de masa","Un color distinto"],["A use-stage improvement that raises relevant manufacture or end-of-life impacts","Any mass reduction","A different colour"],0,"Hay que revisar el sistema completo y los requisitos, no un único indicador.","Review the whole system and requirements, not a single indicator.")]},
    {id:"circularity",title:t("Estrategias de circularidad y conservación de valor","Circularity strategies and value retention"),intro:t("Circularidad no significa simplemente reciclar residuos. Busca mantener producto, componente y material en utilidad segura durante el mayor tiempo y con la menor pérdida de valor técnico viable.","Circularity does not simply mean recycling waste. It seeks to keep products, components and materials safely useful for as long as feasible with the least loss of technical value."),sections:t([
      ["Bucles de mayor valor","Mantener evita crear el residuo; reparar restaura una función; reutilizar conserva el componente. Reacondicionar devuelve condición y remanufacturar reconstruye con controles definidos. Cada opción exige trazabilidad, inspección y autorización apropiadas."],
      ["Nuevas funciones y materiales","Repurpose cambia la función y debe verificar nuevos requisitos. Reciclar recupera material, a menudo con pérdida de propiedades o mezcla. Recuperar energía o valor residual es último recurso cuando bucles de mayor valor no son técnica o legalmente viables."],
      ["Jerarquía condicionada","No existe una secuencia automática. Un componente crítico fatigado no debe reutilizarse por conservar valor; una reparación insegura no es circular. Seguridad, aeronavegabilidad, contaminación, propiedad intelectual y calidad limitan el bucle disponible."],
      ["Diseñar el bucle","La circularidad futura depende hoy de acceso, unión, documentación, repuestos, software, tolerancias y composición. Diseñar una ruta de inspección y recuperación es más sólido que prometer reciclabilidad sin infraestructura ni calidad de salida."]
    ],[
      ["Higher-value loops","Maintain prevents waste; repair restores a function; reuse retains the component. Refurbishment restores condition and remanufacture rebuilds under defined controls. Each option needs appropriate traceability, inspection and authorisation."],
      ["New functions and materials","Repurpose changes the function and must verify new requirements. Recycling recovers material, often with property loss or mixing. Energy or residual-value recovery is a last resort when higher-value loops are not technically or legally feasible."],
      ["Conditional hierarchy","There is no automatic sequence. A fatigue-critical component must not be reused merely to retain value; an unsafe repair is not circular. Safety, airworthiness, contamination, intellectual property and quality constrain the available loop."],
      ["Designing the loop","Future circularity depends today on access, joining, documentation, spares, software, tolerances and composition. Designing an inspection and recovery route is stronger than promising recyclability without infrastructure or output quality."]
    ]),flow:t([["Mantener","Conservar función"],["Reparar/reusar","Conservar componente"],["Reacondicionar","Restaurar valor"],["Reciclar","Recuperar material"]],[["Maintain","Retain function"],["Repair/reuse","Retain component"],["Refurbish","Restore value"],["Recycle","Recover material"]]),caseTitle:t("Unidad electrónica obsoleta","Obsolete electronic unit"),case:t("Una LRU funciona, pero su procesador queda obsoleto. Las opciones son sustituir toda la unidad, actualizar una tarjeta modular o remanufacturar unidades retiradas con pruebas.","An LRU still functions, but its processor is obsolete. Options are replacing the whole unit, upgrading a modular board or remanufacturing removed units with testing."),analysis:t("Prioriza la función segura y compara actualización y remanufactura antes de destrucción material. Verifica configuración, software, trazabilidad, pruebas, disponibilidad y autoridad de aprobación.","Prioritise safe function and compare upgrade and remanufacture before material destruction. Verify configuration, software, traceability, testing, availability and approval authority."),questions:[q(["¿Qué distingue circularidad de reciclaje?","What distinguishes circularity from recycling?"],["Circularidad conserva valor mediante varios bucles; reciclaje es uno de ellos","Son idénticos","Circularidad solo gestiona embalajes"],["Circularity retains value through several loops; recycling is one of them","They are identical","Circularity only manages packaging"],0,"Los bucles de producto y componente suelen conservar más valor que recuperar material.","Product and component loops often retain more value than material recovery."),q(["¿Cuándo no debe forzarse un bucle alto?","When should a high-value loop not be forced?"],["Cuando compromete requisitos técnicos o seguridad","Cuando necesita análisis","Cuando reduce residuos"],["When it compromises technical requirements or safety","When it needs analysis","When it reduces waste"],0,"Circularidad opera dentro de requisitos de seguridad, calidad y conformidad.","Circularity operates within safety, quality and compliance requirements.")]},
    {id:"requirements",title:t("Requisitos de ecodiseño y compromisos de ingeniería","Eco-design requirements and engineering trade-offs"),intro:t("Un objetivo ambiental solo influye de forma controlada si se convierte en requisito, criterio de verificación y decisión de arquitectura junto con los demás requisitos del producto.","An environmental objective only has controlled influence when it becomes a requirement, verification criterion and architecture decision alongside other product requirements."),sections:t([
      ["De aspiración a requisito","Sustituye ‘usar material verde’ por condiciones medibles: función, límite de masa, durabilidad, sustancias restringidas, contenido trazable, desmontaje o tasa de reparación. Define método de verificación, responsable y etapa de revisión."],
      ["Restricciones no negociables","Seguridad y aeronavegabilidad establecen el espacio de solución. Fiabilidad, mantenibilidad y disponibilidad sostienen misión y vida útil. Un criterio ambiental no autoriza relajar márgenes, cualificación o control de configuración."],
      ["Trade-offs visibles","Masa, coste, durabilidad, material disponible, consumo operativo, reparabilidad y aspectos ambientales/sociales pueden competir. Usa una matriz con umbrales obligatorios y criterios ponderados; evita compensar un fallo obligatorio con una ventaja secundaria."],
      ["Decisión a nivel de sistema","Optimizar una pieza puede empeorar mantenimiento, plataforma o cadena. Revisa interfaces, repuestos, herramientas, formación y escenarios de uso. Conserva alternativas descartadas y la evidencia que justificó el compromiso."]
    ],[
      ["From aspiration to requirement","Replace ‘use a green material’ with measurable conditions: function, mass limit, durability, restricted substances, traceable content, disassembly or repair rate. Define verification method, owner and review stage."],
      ["Non-negotiable constraints","Safety and airworthiness define the solution space. Reliability, maintainability and availability support mission and service life. An environmental criterion never authorises relaxing margins, qualification or configuration control."],
      ["Visible trade-offs","Mass, cost, durability, material availability, operational consumption, repairability and environmental/social factors may compete. Use a matrix with mandatory thresholds and weighted criteria; never offset a mandatory failure with a secondary benefit."],
      ["System-level decision","Optimising a part may worsen maintenance, platform or supply. Review interfaces, spares, tools, training and use scenarios. Retain rejected alternatives and the evidence that justified the compromise."]
    ]),flow:t([["Necesidad","Función y contexto"],["Umbrales","Seguridad y conformidad"],["Criterios","Rendimiento y sostenibilidad"],["Verificación","Evidencia y revisión"]],[["Need","Function and context"],["Thresholds","Safety and compliance"],["Criteria","Performance and sustainability"],["Verification","Evidence and review"]]),caseTitle:t("Panel interior de cabina","Cabin interior panel"),case:t("Una alternativa con contenido reciclado reduce material virgen, pero tiene variabilidad, un único proveedor y aún no cumple la prueba de humo. Otra es más pesada, reparable y ya cualificada.","An alternative with recycled content reduces virgin feedstock but has variability, one supplier and has not yet passed smoke testing. Another is heavier, repairable and already qualified."),analysis:t("La primera no supera todavía un umbral obligatorio. Mantén la opción en investigación con plan de cualificación y suministro; compara masa, reparación y vida cuando exista evidencia equivalente. El contenido reciclado no concede superioridad automática.","The first option does not yet pass a mandatory threshold. Keep it under investigation with qualification and supply plans; compare mass, repair and life once equivalent evidence exists. Recycled content gives no automatic superiority."),questions:[q(["¿Cuál es un requisito verificable?","Which is a verifiable requirement?"],["Ser sostenible","Permitir retirar el módulo en 20 minutos con herramientas definidas","Parecer circular"],["Be sustainable","Allow module removal within 20 minutes using defined tools","Look circular"],1,"Incluye condición medible y puede asociarse a un método de verificación.","It includes a measurable condition and can be tied to a verification method."),q(["¿Cómo tratar un fallo de seguridad?","How should a safety failure be treated?"],["Compensarlo con menor masa","Como umbral no satisfecho","Ocultarlo en la puntuación total"],["Offset it with lower mass","As an unmet threshold","Hide it in the total score"],1,"Los criterios obligatorios deben superarse antes de ponderar ventajas.","Mandatory criteria must pass before benefits are weighted.")]},
    {id:"materials",title:t("Decisiones sobre materiales aeronáuticos","Aerospace material decisions"),intro:t("Ningún material es sostenible por sí mismo. La decisión depende de función, procesado, origen, durabilidad, reparación, sustancias, cadena, uso y rutas reales al final de vida.","No material is sustainable in itself. The decision depends on function, processing, origin, durability, repair, substances, supply, use and real end-of-life routes."),sections:t([
      ["Metales y materiales críticos","Aluminio, titanio, aceros y superaleaciones ofrecen propiedades, rutas de reparación y reciclaje diferentes. Aleaciones y elementos críticos pueden concentrar riesgo geográfico. La chatarra limpia conserva más valor que mezclas contaminadas; la trazabilidad importa para calidad y procedencia."],
      ["Composites","Alta prestación y baja masa pueden beneficiar el uso, pero fibras, matrices, adhesivos, curado, daño oculto y uniones dificultan reparación y recuperación. El reciclado puede producir una calidad distinta; debe existir una aplicación y especificación para la salida."],
      ["Polímeros, coatings y tratamientos","Aditivos y recubrimientos aportan fuego, corrosión, desgaste o conductividad. Sustituir una sustancia puede afectar vida y mantenimiento. Evalúa composición, exposición, requisitos químicos, cualificación y consecuencias de una vida menor."],
      ["Trazabilidad y compatibilidad","Identidad de lote, condición, composición y proceso sostienen decisión y recuperación. Mezclas, insertos, contaminación y adhesivos pueden impedir separación. Durabilidad evita reemplazos, pero un diseño durable e inseparable puede bloquear reparación: compara ambas dimensiones."]
    ],[
      ["Metals and critical materials","Aluminium, titanium, steels and superalloys offer different properties, repair and recycling routes. Alloys and critical elements may concentrate geographic risk. Clean scrap retains more value than contaminated mixes; traceability matters for quality and origin."],
      ["Composites","High performance and low mass may benefit use, but fibres, matrices, adhesives, curing, hidden damage and joining complicate repair and recovery. Recycled output may have different quality; an application and specification for that output must exist."],
      ["Polymers, coatings and treatments","Additives and coatings provide fire, corrosion, wear or conductivity performance. Replacing a substance can change life and maintenance. Assess composition, exposure, chemical requirements, qualification and consequences of shorter life."],
      ["Traceability and compatibility","Batch identity, condition, composition and process support decisions and recovery. Mixtures, inserts, contamination and adhesives may prevent separation. Durability avoids replacement, but a durable inseparable design may block repair: compare both dimensions."]
    ]),flow:t([["Propiedad","Función técnica"],["Proceso","Energía y sustancias"],["Servicio","Daño y reparación"],["Salida","Separación y calidad"]],[["Property","Technical function"],["Process","Energy and substances"],["Service","Damage and repair"],["Output","Separation and quality"]]),caseTitle:t("Protección anticorrosión","Corrosion protection"),case:t("Un coating alternativo evita una sustancia preocupante, pero los ensayos preliminares indican la mitad de vida en ambiente salino. El acceso para repintado exige retirar equipos.","An alternative coating avoids a substance of concern, but early tests indicate half the life in saline conditions. Recoating access requires equipment removal."),analysis:t("Compara peligro químico, exposición, frecuencia de mantenimiento, indisponibilidad, residuos y protección del sustrato. Pide ensayo representativo y analiza rediseño de acceso; no aceptes ni rechaces solo por la sustitución química.","Compare chemical hazard, exposure, maintenance frequency, downtime, waste and substrate protection. Request representative testing and analyse access redesign; neither accept nor reject on chemical substitution alone."),questions:[q(["¿Qué afirmación es técnicamente prudente?","Which statement is technically prudent?"],["El reciclado siempre supera al virgen","La alternativa depende de función, proceso, vida y salida real","El composite nunca puede repararse"],["Recycled always outperforms virgin","The alternative depends on function, process, life and actual output","Composite can never be repaired"],1,"La comparación necesita contexto y evidencia específica.","The comparison needs specific context and evidence."),q(["¿Por qué importa la contaminación?","Why does contamination matter?"],["Puede degradar separación y calidad del material recuperado","Solo cambia el color","Garantiza circularidad"],["It can degrade separation and recovered-material quality","It only changes colour","It guarantees circularity"],0,"La calidad y compatibilidad determinan si existe una ruta de recuperación útil.","Quality and compatibility determine whether a useful recovery route exists.")]},
    {id:"service-design",title:t("Diseño para mantenimiento, reparación, actualización y desmontaje","Design for maintenance, repair, upgrade and disassembly"),intro:t("La vida útil no se extiende por intención. Se habilita mediante arquitectura, acceso, inspección, interfaces, documentación y disponibilidad de componentes.","Service life is not extended by intention. It is enabled through architecture, access, inspection, interfaces, documentation and component availability."),sections:t([
      ["Modularidad y actualización","Separa funciones con ritmos de obsolescencia distintos y define interfaces estables. Un módulo reemplazable puede evitar sustituir el conjunto, pero añade conectores, masa y puntos de fallo. Evalúa granularidad y configuración."],
      ["Acceso e inspección","Diseña zonas visibles, espacio para herramienta, datos de condición y métodos no destructivos cuando proceda. El tiempo, riesgo y daño inducido al acceder forman parte de la mantenibilidad y de la decisión de reparación."],
      ["Uniones reversibles y permanentes","Fasteners facilitan desmontaje pero agregan masa, concentraciones de tensión y mantenimiento. Adhesivos o soldadura pueden mejorar prestación, pero dificultar separación. Selecciona la unión según carga, entorno, inspección, reparación y recuperación."],
      ["Recuperación controlada","Marca materiales y configuración, conserva instrucciones, define criterios de aceptación y evita contaminar piezas. Recuperar un componente requiere condición conocida y autoridad; desmontar sin cadena de evidencia no equivale a reutilización aeronáutica."]
    ],[
      ["Modularity and upgrade","Separate functions with different obsolescence rates and define stable interfaces. A replaceable module can avoid replacing the assembly, but adds connectors, mass and failure points. Assess granularity and configuration."],
      ["Access and inspection","Design visible zones, tool clearance, condition data and non-destructive methods where appropriate. Time, risk and access-induced damage are part of maintainability and the repair decision."],
      ["Reversible and permanent joining","Fasteners enable disassembly but add mass, stress concentrations and maintenance. Adhesive bonding or welding may improve performance but hinder separation. Select joining for load, environment, inspection, repair and recovery."],
      ["Controlled recovery","Mark materials and configuration, retain instructions, define acceptance criteria and avoid contamination. Component recovery needs known condition and authority; disassembly without an evidence chain does not equal aerospace reuse."]
    ]),flow:t([["Acceder","Sin daño inducido"],["Inspeccionar","Condición conocida"],["Intervenir","Reparar/actualizar"],["Recuperar","Identidad y aceptación"]],[["Access","No induced damage"],["Inspect","Known condition"],["Intervene","Repair/upgrade"],["Recover","Identity and acceptance"]]),caseTitle:t("Carenado unido permanentemente","Permanently joined fairing"),case:t("Un carenado adhesivado ahorra masa y montaje, pero una válvula de vida corta queda detrás. Cada sustitución destruye el carenado y genera días de indisponibilidad.","A bonded fairing saves mass and assembly time, but a short-life valve sits behind it. Each replacement destroys the fairing and creates days of downtime."),analysis:t("Revisa arquitectura y acceso, no solo la unión. Compara panel de servicio, módulo de válvula, fasteners híbridos y vida alineada. Incluye masa, fatiga, sellado, inspección, tiempo, residuos y cualificación.","Review architecture and access, not just joining. Compare a service panel, valve module, hybrid fasteners and aligned life. Include mass, fatigue, sealing, inspection, time, waste and qualification."),questions:[q(["¿Qué habilita actualización efectiva?","What enables effective upgrading?"],["Interfaces y control de configuración definidos","Más adhesivo","Ocultar componentes"],["Defined interfaces and configuration control","More adhesive","Hiding components"],0,"La modularidad necesita interfaces técnicas y trazabilidad de configuración.","Modularity needs technical interfaces and configuration traceability."),q(["¿Qué debe acompañar a un componente recuperado?","What should accompany a recovered component?"],["Solo una foto","Condición, identidad, criterios y autoridad aplicables","Una promesa de reciclaje"],["A photo only","Applicable condition, identity, criteria and authority","A recycling promise"],1,"Desmontaje físico sin evidencia no demuestra aptitud para reutilización.","Physical removal without evidence does not demonstrate fitness for reuse.")]},
    {id:"evidence",title:t("Decisiones de diseño circular basadas en evidencia","Evidence-based circular design decisions"),intro:t("Una decisión defendible muestra alternativas, hipótesis, fuentes, límites y autoridad. La incertidumbre no desaparece: se hace visible y se gestiona en revisiones sucesivas.","A defensible decision shows alternatives, assumptions, sources, limits and authority. Uncertainty does not disappear: it is made visible and managed through successive reviews."),sections:t([
      ["Comparación trazable","Registra función, límites, alternativas y criterios. Separa datos medidos, declaraciones de proveedor, cálculos, proxies y juicio experto. Fecha y versiona fuentes para que otra persona pueda reconstruir la decisión."],
      ["Información incompleta","Clasifica gaps por capacidad de cambiar la decisión. Usa rangos y escenarios, no precisión falsa. Una decisión condicionada debe indicar controles temporales, evidencia pendiente, responsable, fecha y condición de caducidad."],
      ["Gates de revisión","En requisitos valida alcance y métricas; en concepto compara arquitecturas; en diseño preliminar confirma riesgos; en diseño crítico exige evidencia suficiente para compromisos. Tras cambios de material, proceso, proveedor o uso, reabre supuestos afectados."],
      ["Claims proporcionados","Evita ‘cero impacto’, ‘material verde’ o ‘100 % circular’ sin alcance demostrable. Expresa qué indicador mejora, frente a qué referencia, en qué escenario, con qué fuente y qué impactos no se evaluaron."]
    ],[
      ["Traceable comparison","Record function, boundaries, alternatives and criteria. Separate measured data, supplier declarations, calculations, proxies and expert judgement. Date and version sources so another person can reconstruct the decision."],
      ["Incomplete information","Classify gaps by their ability to change the decision. Use ranges and scenarios, not false precision. A conditional decision must identify temporary controls, pending evidence, owner, date and expiry condition."],
      ["Review gates","At requirements, validate scope and metrics; at concept, compare architectures; at preliminary design, confirm risks; at critical design, require enough evidence for commitments. After changes in material, process, supplier or use, reopen affected assumptions."],
      ["Proportionate claims","Avoid ‘zero impact’, ‘green material’ or ‘100% circular’ without a demonstrable scope. State which indicator improves, against which baseline, in which scenario, with which source and what was not assessed."]
    ]),flow:t([["Pregunta","Qué decisión"],["Evidencia","Fuente y calidad"],["Incertidumbre","Gap y sensibilidad"],["Gate","Autoridad y acción"]],[["Question","Which decision"],["Evidence","Source and quality"],["Uncertainty","Gap and sensitivity"],["Gate","Authority and action"]]),caseTitle:t("Claim de material circular","Circular-material claim"),case:t("Un proveedor declara ‘panel 100 % circular’. Aporta porcentaje de contenido reciclado, pero no composición completa, tasa de rechazo, vida, reparabilidad ni destino tras servicio.","A supplier claims a ‘100% circular panel’. It provides recycled-content percentage but no full composition, reject rate, life, repairability or post-service destination."),analysis:t("No conviertas el claim en conclusión. Define la comparación, solicita evidencia de composición y cadena, valida prestación y vida, identifica rutas reales y reformula cualquier comunicación con alcance y límites.","Do not turn the claim into a conclusion. Define the comparison, request composition and chain evidence, validate performance and life, identify real routes and restate any communication with scope and limits."),questions:[q(["¿Cómo gestionar un dato faltante crítico?","How should a critical missing datum be managed?"],["Inventar un promedio","Registrar el gap, probar sensibilidad y condicionar la decisión","Borrarlo del acta"],["Invent an average","Record the gap, test sensitivity and condition the decision","Delete it from the record"],1,"La incertidumbre visible permite controles y revisión posterior.","Visible uncertainty enables controls and later review."),q(["¿Qué claim es más defendible?","Which claim is more defensible?"],["Impacto cero","Reduce un indicador definido frente a una referencia y escenario documentados","Material verde absoluto"],["Zero impact","Reduces a defined indicator against a documented baseline and scenario","Absolutely green material"],1,"El alcance, referencia, fuente y límites evitan una simplificación engañosa.","Scope, baseline, source and limits avoid misleading simplification.")]}
  ];
  const finalExercise={id:"final",title:t("Ejercicio integrado · Retrofit de panel de misión","Integrated exercise · Mission-panel retrofit"),intro:t("Una flota necesita modernizar un panel protector de equipos. Alternativa A: aluminio reparable y cualificado, más pesado, con suministro estable. B: composite ligero de un solo proveedor, larga vida teórica, reparación compleja y salida incierta. C: panel híbrido modular, masa intermedia, acceso rápido, coating aún en cualificación y trazabilidad parcial de un elemento crítico. Construye una decisión defendible.","A fleet must modernise an equipment protection panel. Alternative A: repairable qualified aluminium, heavier, with stable supply. B: lightweight single-source composite, long theoretical life, complex repair and uncertain output route. C: modular hybrid panel, medium mass, rapid access, coating still in qualification and partial traceability for a critical element. Build a defensible decision."),decisions:[
    q(["1. ¿Cómo enmarcas la comparación?","1. How do you frame the comparison?"],["Solo masa de compra","Función, vida, misión, límites y escenarios equivalentes","Elegir el material más nuevo"],["Purchase mass only","Equivalent function, life, mission, boundaries and scenarios","Choose the newest material"],1,"La función y escenarios evitan conclusiones basadas en una diferencia aislada.","Function and scenarios prevent conclusions based on an isolated difference."),
    q(["2. ¿Qué haces con la modularidad de C?","2. What do you do with C's modularity?"],["La das por circular automáticamente","Verificas acceso, interfaces, masa, fallos, repuestos y recuperación","Ignoras mantenimiento"],["Call it circular automatically","Verify access, interfaces, mass, failures, spares and recovery","Ignore maintenance"],1,"La modularidad aporta valor solo si funciona dentro del sistema técnico y logístico.","Modularity adds value only when it works within the technical and logistics system."),
    q(["3. ¿Cómo tratas coating y material crítico?","3. How do you treat coating and critical material?"],["Apruebas por menor masa","Mantienes gaps separados, plan de cualificación/trazabilidad y decisión condicionada","Asumes que el proveedor resolverá"],["Approve because of lower mass","Keep separate gaps, qualification/traceability plans and a conditional decision","Assume the supplier will solve it"],1,"Requisitos técnicos y riesgo de suministro necesitan evidencias y responsables específicos.","Technical requirements and supply risk need specific evidence and owners."),
    q(["4. ¿Qué recomendación es defendible ahora?","4. Which recommendation is defensible now?"],["Una selección absoluta sin supuestos","Una recomendación por escenarios con umbrales, trade-offs, evidencia, incertidumbres y gate de revisión","Declarar impacto cero"],["An absolute selection without assumptions","A scenario recommendation with thresholds, trade-offs, evidence, uncertainties and a review gate","Declare zero impact"],1,"La decisión conserva trazabilidad y puede cambiar cuando llegue evidencia relevante.","The decision retains traceability and can change when relevant evidence arrives.")
  ]};
  const stateKey="sn-course-eco-design-circularity-aerospace-materials-v1";let language=new URLSearchParams(location.search).get("hubLang")==="en"?"en":"es",current=0,state={visited:[],attempted:[],finalReviewed:false};try{state={...state,...JSON.parse(localStorage.getItem(stateKey)||"{}")};}catch(_){ }const all=[...modules,finalExercise],$=s=>document.querySelector(s),save=()=>{try{localStorage.setItem(stateKey,JSON.stringify(state));}catch(_){ }},announce=m=>{$("#course-live").textContent="";requestAnimationFrame(()=>{$("#course-live").textContent=m;});};
  function applyCopy(){document.documentElement.lang=language;document.title=copy.title[language];document.querySelectorAll("[data-copy]").forEach(n=>{const item=copy[n.dataset.copy];if(item&&typeof item[language]==="string")n.textContent=item[language];});document.querySelectorAll("[data-language]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.language===language)));$("#hub-link").href=`../?hubLang=${language}#learning-paths`;$("#objectives-list").innerHTML=objectives[language].map(x=>`<li>${x}</li>`).join("");}
  function nav(){const firstIncomplete=modules.findIndex(m=>!state.attempted.includes(m.id)),lastUnlocked=firstIncomplete===-1?modules.length:firstIncomplete;$("#module-list").innerHTML=all.map((item,index)=>`<li><button type="button" data-module="${index}" class="${state.visited.includes(item.id)?"visited":""}" ${index===current?'aria-current="step"':''} ${index>lastUnlocked?"disabled":""}><span>${index<modules.length?`${copy.module[language]} ${index+1}`:copy.final[language]}</span><br><small>${item.title[language]}</small></button></li>`).join("");const count=new Set(state.visited).size;$("#progress-label").textContent=`${count} / ${all.length}`;$("#course-progress").value=count;$("#course-progress").setAttribute("aria-label",`${copy.progress[language]}: ${count} / ${all.length}`);document.querySelectorAll("[data-module]:not(:disabled)").forEach(b=>b.addEventListener("click",()=>show(Number(b.dataset.module))));}
  const visual=items=>`<div class="visual-explainer"><div class="visual-flow">${items.map((item,index)=>`${index?'<b aria-hidden="true">→</b>':""}<div><strong>${item[0]}</strong><span>${item[1]}</span></div>`).join("")}</div></div>`;
  function questions(module,index){return `<section class="knowledge-check" aria-labelledby="check-title-${index}"><h3 id="check-title-${index}">${copy.check[language]}</h3>${module.questions.map((item,qi)=>`<fieldset><legend>${item.q[language]}</legend>${item.options[language].map((option,oi)=>`<label class="option"><input type="radio" name="m${index}q${qi}" value="${oi}"> ${option}</label>`).join("")}<div id="feedback-${index}-${qi}" class="check-feedback" hidden></div></fieldset>`).join("")}<button type="button" data-check="${index}">${copy.checkAction[language]}</button><p id="check-summary-${index}" role="status"></p></section>`;}
  function renderModule(module,index){const sections=module.sections[language];$("#module-content").innerHTML=`<p class="module-number">${copy.module[language]} ${index+1} · 25 min</p><h2>${module.title[language]}</h2><p class="module-intro">${module.intro[language]}</p><section class="learning-block"><h3>${copy.concepts[language]}</h3>${sections.map(s=>`<h4>${s[0]}</h4><p>${s[1]}</p>`).join("")}</section>${visual(module.flow[language])}<section class="case"><h3>${copy.miniCase[language]} · ${module.caseTitle[language]}</h3><p>${module.case[language]}</p><p class="case-analysis"><strong>${copy.analysis[language]}:</strong> ${module.analysis[language]}</p></section>${questions(module,index)}`;$("[data-check]").addEventListener("click",()=>checkModule(module,index));}
  function checkModule(module,index){const answers=module.questions.map((_,qi)=>document.querySelector(`input[name="m${index}q${qi}"]:checked`));if(answers.some(a=>!a)){ $("#check-summary-"+index).textContent=copy.answerAll[language];return;}let score=0;module.questions.forEach((item,qi)=>{const ok=Number(answers[qi].value)===item.correct;if(ok)score++;const box=$("#feedback-"+index+"-"+qi);box.hidden=false;box.className=`check-feedback ${ok?"correct":"review"}`;box.textContent=`${ok?copy.correct[language]:copy.reviewAnswer[language]}${item.feedback[language]}`;});if(!state.attempted.includes(module.id))state.attempted.push(module.id);save();$("#check-summary-"+index).textContent=copy.result[language](score);announce($("#check-summary-"+index).textContent);buttons();nav();}
  function completionMarkup(){return `<section id="course-complete" class="completion active" tabindex="-1"><h3>${copy.completedTitle[language]}</h3><p>${copy.completedBody[language]}</p><p>${copy.revisit[language]}</p></section>`;}
  function renderFinal(){$("#module-content").innerHTML=`<p class="module-number">${copy.final[language]} · 40 min</p><h2>${finalExercise.title[language]}</h2><p class="module-intro">${finalExercise.intro[language]}</p><div class="final-grid">${finalExercise.decisions.map((d,di)=>`<fieldset class="final-card"><legend>${d.q[language]}</legend>${d.options[language].map((o,oi)=>`<label class="option"><input type="radio" name="final${di}" value="${oi}"> ${o}</label>`).join("")}<div id="final-feedback-${di}" class="check-feedback" hidden></div></fieldset>`).join("")}</div><button type="button" class="final-submit">${copy.finalAction[language]}</button><p id="final-status" role="status"></p>${state.finalReviewed?completionMarkup():""}`;$(".final-submit").addEventListener("click",reviewFinal);}
  function reviewFinal(){const answers=finalExercise.decisions.map((_,di)=>document.querySelector(`input[name="final${di}"]:checked`));if(answers.some(a=>!a)){ $("#final-status").textContent=copy.finalIncomplete[language];announce(copy.finalIncomplete[language]);return;}finalExercise.decisions.forEach((d,di)=>{const ok=Number(answers[di].value)===d.correct,box=$("#final-feedback-"+di);box.hidden=false;box.className=`check-feedback ${ok?"correct":"review"}`;box.textContent=`${ok?copy.correct[language]:copy.reviewAnswer[language]}${d.feedback[language]}`;});state.finalReviewed=true;save();if(!$("#course-complete"))$("#module-content").insertAdjacentHTML("beforeend",completionMarkup());nav();$("#course-complete").focus();announce(copy.completedTitle[language]);}
  function buttons(){$("#previous-module").disabled=current===0;$("#next-module").hidden=current===all.length-1;if(current<modules.length){const attempted=state.attempted.includes(modules[current].id);$("#next-module").disabled=!attempted;$("#next-module").textContent=current===modules.length-1?copy.finish[language]:copy.next[language];}}
  function show(index){current=Math.max(0,Math.min(index,all.length-1));const item=all[current];if(!state.visited.includes(item.id))state.visited.push(item.id);save();applyCopy();nav();if(current<modules.length)renderModule(modules[current],current);else renderFinal();buttons();$("#module-content").focus();}
  document.querySelectorAll("[data-language]").forEach(b=>b.addEventListener("click",()=>{language=b.dataset.language;const url=new URL(location.href);url.searchParams.set("hubLang",language);history.replaceState(null,"",url);show(current);}));$("#previous-module").addEventListener("click",()=>show(current-1));$("#next-module").addEventListener("click",()=>show(current+1));show(0);
})();
