"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),zlib=require("node:zlib"),vm=require("node:vm");
const catalogue=require("../catalogue-data.js"),paths=require("../learning-paths-data.js"),selectors=require("../learning-paths.js"),store=require("../progress-store.js"),serviceApi=require("../progress-service.js");
const resourceId="reach-compliance-challenge",resource=catalogue.resources.find(x=>x.id===resourceId),dir=path.resolve(__dirname,"..",resourceId);
const loader=fs.readFileSync(path.join(dir,"index.html"),"utf8"),localisation=fs.readFileSync(path.join(dir,"spanish-translations.js"),"utf8"),chunks=Array.from({length:11},(_,i)=>fs.readFileSync(path.join(dir,`part-${String(i+1).padStart(2,"0")}.txt`),"utf8")).join("");
const english=zlib.gunzipSync(Buffer.from(chunks,"base64")).toString("utf8"),context={};vm.createContext(context);vm.runInContext(localisation,context);const spanish=context.SNReachLocalize(english);

test("keeps one bilingual REACH identity and catalogue total 26",()=>{assert.equal(catalogue.resources.length,26);assert.equal(catalogue.resources.filter(x=>x.id===resourceId).length,1);assert.deepEqual(resource.launches,{es:"reach-compliance-challenge/",en:"reach-compliance-challenge/"});assert.deepEqual(resource.languages,["es","en"]);assert.deepEqual(resource.provenance[0].languages,["es","en"]);});
test("keeps six paths and all revisions unchanged",()=>{assert.equal(paths.paths.length,6);assert.deepEqual(Object.fromEntries(paths.paths.map(x=>[x.id,x.revision])),{"sustainable-aviation-foundations":1,"eco-design-circularity-materials":3,"responsible-supply-chain-compliance":3,"sustainable-in-service-operations":1,"nature-habitat-operational-risk":1,"evidence-systems-decision-making":1});assert.deepEqual(paths.paths.flatMap(x=>x.steps).filter(x=>x.resourceId===resourceId).map(x=>x.id).sort(),["eco-design-reach","supply-reach"]);});
test("derives real Spanish coverage while English remains complete",()=>{const eco=paths.paths.find(x=>x.id==="eco-design-circularity-materials"),supply=paths.paths.find(x=>x.id==="responsible-supply-chain-compliance");assert.deepEqual(selectors.languageAvailability(eco,catalogue,"es"),{language:"es",status:"partial",availableRequired:4,totalRequired:7});assert.deepEqual(selectors.languageAvailability(eco,catalogue,"en"),{language:"en",status:"complete",availableRequired:7,totalRequired:7});assert.deepEqual(selectors.languageAvailability(supply,catalogue,"es"),{language:"es",status:"partial",availableRequired:3,totalRequired:5});assert.deepEqual(selectors.languageAvailability(supply,catalogue,"en"),{language:"en",status:"complete",availableRequired:5,totalRequired:5});});
test("localises the exact English state machine and all eighteen stages",()=>{const renders=/function render(?:Cover|Synopsis|Map|TheoryReach|Passports|TheoryFunction|Substitution|TheoryAlternatives|Stack|TheorySystem|Maintenance|TheoryLifecycle|Exposure|TheoryExposure|Gates|TheoryCertification|Board|Final)\(/g;for(const source of [english,spanish]){assert.equal((source.match(/if\(p===/g)||[]).length,18);assert.match(source,/if\(p===17\) return renderFinal\(\)/);assert.equal((source.match(renders)||[]).length,18);for(const [token,count] of [["data-hotspot=",1],["data-sub=",1],["data-stack=",5],["data-maint=",1],["data-exp=",3],["data-gate=",1],["class=\"final-score\"",1]])assert.equal(source.split(token).length-1,count,token);for(const token of ["state.maintenanceAttempts>=2","state.exposureAttempts>=2","state.stackAttempts>=2","state.subAttempts[k]>=2","state.gates.size===4"])assert.ok(source.includes(token),token);}assert.match(spanish,/El Reto de Cumplimiento REACH/);assert.match(spanish,/Laboratorio de sustitución/);assert.match(spanish,/Constructor del sistema de protección/);assert.match(spanish,/Simulador de exposición laboral/);assert.match(spanish,/Comité de Revisión de Diseño/);assert.match(spanish,/u\.lang='es-ES'/);assert.doesNotThrow(()=>[...spanish.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].forEach(m=>new vm.Script(m[1])));});
test("preserves calculations, state properties, answer logic, retries, gates and final selector",()=>{for(const token of ["const STACK_SOLUTION={pretreatment:'clean',conversion:'tcc',primer:'p40',sealant:'s21',topcoat:'tc'}","choice==='brush'","s<=4?'low':s<=6?'medium':'high'","Object.values(g).every(x=>x.ok)","class=\"final-score\""]){assert.ok(english.includes(token));assert.ok(spanish.includes(token));}const stateProperties=source=>[...source.matchAll(/state\.([A-Za-z_]+)/g)].map(match=>match[1]).sort();assert.deepEqual(stateProperties(spanish),stateProperties(english));assert.match(loader,/data-completion-selector="\.final-score"/);assert.match(loader,/selectedLanguage === "es" \? window\.SNReachLocalize\(html\) : html/);});
test("shares one completion record across English and Spanish",()=>{const storage=store.createMemoryStorage();let service=serviceApi.createBrowserService(catalogue,paths,storage);service.completeResource(resourceId,{language:"en",source:"manual"});service=serviceApi.createBrowserService(catalogue,paths,storage);assert.equal(service.getState().resources[resourceId].status,"completed");assert.equal(Object.keys(service.getState().resources).filter(x=>x===resourceId).length,1);const esStorage=store.createMemoryStorage();service=serviceApi.createBrowserService(catalogue,paths,esStorage);service.reportInternalCompletion(resourceId,"es");service=serviceApi.createBrowserService(catalogue,paths,esStorage);assert.equal(service.getState().resources[resourceId].status,"completed");assert.equal(Object.keys(service.getState().resources).filter(x=>x===resourceId).length,1);});
test("preserves English payload and accessible two-way language switching",()=>{assert.match(loader,/spanish-translations\.js/);assert.match(loader,/part-01\.txt/);assert.match(loader,/DecompressionStream\("gzip"\)/);assert.match(loader,/Cambiar al español/);assert.match(localisation,/Escuchar a ARIA/);assert.match(localisation,/ARIA, guía digital de materiales y cumplimiento/);});
