"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const catalogue=require("../catalogue-data.js"),paths=require("../learning-paths-data.js"),store=require("../progress-store.js"),serviceApi=require("../progress-service.js"),selectors=require("../progress-selectors.js");
const root=path.resolve(__dirname,".."),dir=path.join(root,"supply-chain-compliance-decision-review");
test("registers one bilingual internal scenario assessment",()=>{const r=catalogue.resources.find(x=>x.id==="supply-chain-compliance-decision-review");assert.ok(r);assert.equal(r.kind,"quiz");assert.equal(r.subtype,"scenario-assessment");assert.deepEqual(r.languages,["es","en"]);assert.deepEqual(r.launches,{es:"supply-chain-compliance-decision-review/",en:"supply-chain-compliance-decision-review/"});assert.deepEqual(r.duration,{min:75,max:75,unit:"minutes"});assert.equal(r.difficulty,"intermediate");assert.equal(r.internalAssessment,true);});
test("adds a final required Assess step and changes only the Supply Chain revision",()=>{const p=paths.paths.find(x=>x.id==="responsible-supply-chain-compliance"),s=p.steps.find(x=>x.id==="supply-decision-review");assert.equal(p.revision,3);assert.equal(s.resourceId,"supply-chain-compliance-decision-review");assert.equal(s.requirement,"required");assert.equal(s.intention,"assess");assert.equal(s.finalAssessment,true);assert.equal(paths.paths.find(x=>x.id==="eco-design-circularity-materials").revision,2);assert.ok(paths.paths.filter(x=>![p.id,"eco-design-circularity-materials"].includes(x.id)).every(x=>x.revision===1));for(const id of ["supply-foundations","supply-phytosanitary","supply-reach","supply-ethical","supply-minerals","supply-resilience"])assert.ok(p.steps.some(x=>x.id===id));});
test("implements six scenarios, eighteen applied decisions, thematic review and exact final state",()=>{const js=fs.readFileSync(path.join(dir,"review.js"),"utf8"),html=fs.readFileSync(path.join(dir,"index.html"),"utf8"),css=fs.readFileSync(path.join(dir,"styles.css"),"utf8");assert.doesNotThrow(()=>new vm.Script(js));for(const id of ["origin","rights","chemical","packaging","obsolescence","conditional"])assert.match(js,new RegExp(`id:\\"${id}\\"`));assert.equal((js.match(/d\(\[/g)||[]).length,18);for(const theme of ["traceability","evidence","due","regulatory","logistics","escalation","governance"])assert.match(js,new RegExp(theme));assert.match(js,/allAttempted\(\)/);assert.match(js,/state\.final=true/);assert.match(html,/data-completion-selector="#decision-review-complete\.active"/);assert.match(js,/not a formal grade, certification or proof of professional competence/i);assert.match(css,/@media\(max-width:420px\)/);assert.match(css,/focus-visible/);});
test("preserves Supply Chain revisions 1 and 2 and leaves the new assessment outstanding",()=>{const storage=store.createMemoryStorage();const make=(data,time)=>serviceApi.createBrowserService(catalogue,data,storage,()=>time);const v1=JSON.parse(JSON.stringify(paths)),p1=v1.paths.find(x=>x.id==="responsible-supply-chain-compliance");p1.revision=1;p1.steps=p1.steps.filter(x=>!["supply-foundations","supply-decision-review"].includes(x.id));let s=make(v1,"2026-08-01T10:00:00.000Z");s.startPath(p1.id,"en");for(const x of p1.steps.filter(x=>x.requirement==="required"))s.completeResource(x.resourceId,{pathId:p1.id,stepId:x.id,language:"en",source:"manual"});const v2=JSON.parse(JSON.stringify(paths)),p2=v2.paths.find(x=>x.id===p1.id);p2.revision=2;p2.steps=p2.steps.filter(x=>x.id!=="supply-decision-review");s=make(v2,"2026-08-02T10:00:00.000Z");for(const x of p2.steps.filter(x=>x.requirement==="required"))s.completeResource(x.resourceId,{pathId:p2.id,stepId:x.id,language:"en",source:"manual"});const current=make(paths,"2026-08-03T10:00:00.000Z"),state=current.getState(),record=state.paths[p1.id],summary=selectors.pathSummary(state,paths.paths.find(x=>x.id===p1.id),catalogue),next=selectors.nextActivity(state,paths.paths.find(x=>x.id===p1.id),catalogue);assert.deepEqual(record.completionHistory.map(x=>x.pathRevision).sort(),[1,2]);assert.equal(summary.status,"update_available");assert.equal(next.step.id,"supply-decision-review");assert.equal(record.steps["supply-decision-review"],undefined);assert.ok(record.completionHistory.every(x=>!x.requiredStepEvidence.some(e=>e.resourceId==="supply-chain-compliance-decision-review")));});
test("strict bridge only accepts the explicit reviewed-final selector",()=>{const b=fs.readFileSync(path.join(root,"progress-bridge.js"),"utf8"),s=fs.readFileSync(path.join(root,"progress-service.js"),"utf8");assert.match(b,/"supply-chain-compliance-decision-review": "#decision-review-complete\.active"/);assert.match(s,/AUTOMATIC_INTERNAL_IDS[^\n]+supply-chain-compliance-decision-review/);});
